import { AI_MODEL, aiClient } from "./ai";
import type { ConnectionMetrics, DataHealthReport } from "./profitability";
import { computeConnectionMetrics } from "./profitability";
import { formatCurrency } from "./format";
import { prisma } from "./prisma";
import {
  computeWeekOverWeek,
  rebuildPending,
  renderWeekOverWeek,
  weekOverWeekForModel,
  type BasisInfo,
  type WeekOverWeekReport,
} from "./weekOverWeek";
import {
  cleanDigestText,
  findSummaryProblems,
  withoutOpenJobUnderspend,
  withoutSentences,
  type SummaryFacts,
  type SummaryProblem,
} from "./digestText";
import { getOpportunityData } from "./opportunityData";
import {
  briefTileJobs,
  computeBriefHeadline,
  snapshotFromFeed,
  type BriefHeadline,
  type BriefOpportunitySnapshot,
  type BriefTileJobs,
} from "./briefHeadline";

/** A reply this short on time would only be cut off; the brief goes without it instead. */
const MIN_AI_MS = 15_000;

/**
 * The summary couldn't be written because the run was short on time, not
 * because the AI failed: there wasn't time to ask at all, or the request
 * that failed had been given a shorter wait or no second try to fit the
 * deadline. The weekly send defers the company to its next run instead of
 * sending that week's brief without the summary.
 */
export class SummaryOutOfTimeError extends Error {
  constructor(message = "There wasn't enough time left in this run to write the summary.") {
    super(message);
    this.name = "SummaryOutOfTimeError";
  }
}

/**
 * Limits for one write-up request that must finish `leftMs` from now: the
 * preferred timeout, or less when the run is short on time, with a retry
 * only when two tries still fit. `limited` is true when the deadline cut the
 * request down from what it normally gets. Null when there isn't time to
 * ask at all. Pure, for tests.
 */
export function aiAttemptPlan(
  leftMs: number,
  preferredMs: number
): { timeoutMs: number; retries: number; limited: boolean } | null {
  if (leftMs < MIN_AI_MS) return null;
  const timeoutMs = Math.min(preferredMs, leftMs);
  const retries = leftMs >= 2 * timeoutMs + 1_000 ? 1 : 0;
  return { timeoutMs, retries, limited: timeoutMs < preferredMs || retries === 0 };
}

/**
 * Where the weekly send keeps the summary it wrote, inside the stored
 * metrics (a JSON column, so no schema change). A send that has to be tried
 * again (the email provider couldn't take it, or the run died partway) uses
 * the same summary rather than writing a new one: the recipients who already
 * have the brief and the ones who get it later read the same words, and a
 * retry late in a run can't lose it to the deadline. The Generate button
 * overwrites the metrics without it, so a brief generated by hand is never
 * reused for the scheduled send.
 */
const SEND_SUMMARY_KEY = "briefSendSummary";

/** The stored metrics with the summary this send wrote, when it wrote one. Pure, for tests. */
export function withSummaryForRetry<T extends object>(
  metrics: T,
  brief: { kind: "narrative" | "data_health"; body: string; summaryMissing: boolean }
): T {
  if (brief.kind !== "narrative" || brief.summaryMissing || !brief.body.trim()) return metrics;
  return { ...metrics, [SEND_SUMMARY_KEY]: brief.body };
}

/** The summary an earlier try at this week's send wrote, or null. Pure, for tests. */
export function summaryToReuse(storedMetrics: unknown): string | null {
  if (!storedMetrics || typeof storedMetrics !== "object") return null;
  const text = (storedMetrics as Record<string, unknown>)[SEND_SUMMARY_KEY];
  return typeof text === "string" && text.trim() ? text : null;
}

/** In place of the written summary when it couldn't be written. Says so, and claims nothing else. */
export const SUMMARY_UNAVAILABLE =
  "The written summary couldn't be produced this week, so this brief has the figures only. Every figure above is calculated from your QuickBooks data, and your dashboard has the full picture.";

const SYSTEM_PROMPT = `You write the narrative part of a weekly job-cost email for a contractor who runs their business on QuickBooks Online.

What the data means. Read this before anything else:
- "jobs" are the jobs that matter now: every job still open, plus jobs with any activity in the last 90 days. Older finished jobs are left out on purpose.
- "jobs" and "totals" are JOB-TO-DATE figures: everything billed and spent on each job over its whole life. They are NOT this week's activity. Never say a job did something "this week" based on them, and never describe the totals as what "the week" produced.
- "estimatedRevenue" is the job's contract value. "overUnderBilling" (open jobs only) is billed to date minus the revenue earned by the work done so far: positive means billed ahead of the work, negative means work done that hasn't been billed yet. "percentComplete" is how far along the job is (0 to 1). When "overUnderBilling" or "percentComplete" is null, progress can't be measured on that job (no contract value, no cost estimate or percent complete, costs already past the estimate, or no activity in 90 days). Null is not zero: never call such a job 0% complete, fully billed, or on track with its billing, and don't count it as work done but not billed. "forecastMarginPct", when present, is the margin the job is on track to finish at. It is left out on plans without forecasts, and when the job's progress can't be measured well enough to forecast (too little billed, billing behind the work, or costs already past the estimate). When it is missing, never work out or describe a forecast yourself.
- An open job's "marginPct" is margin to date and mostly reflects billing timing. Never call an open job unprofitable or below target from marginPct alone, and never call marginPct a forecast or say a job is "on track for" or "forecasting" it. Use forecastMarginPct when it is there, and otherwise talk about spend against the estimate and what has been billed.
- "weekOverWeek" is the only source for what changed since the last brief. A deterministic "What changed" section built from it is shown to the reader directly above your text, word for word. Do not repeat it line by line. You may refer to it ("the new costs on Torres Kitchen above").
- If weekOverWeek.noComparisonReason is set, there is no usable previous brief to compare against. Do not speculate about what changed, and do not repeat or explain the reason: the section above already says it.

Accuracy rules, no exceptions:
- Use ONLY the numbers provided. Never estimate, round persuasively, or invent a figure. Every claim must be traceable to a field in the input.
- Over budget is not a loss. Only a completed job can have "lost money": its actual cost exceeds its actual revenue (marginPct below zero). A job that ran $6,600 over its estimate but still has a 28% margin went over budget and stayed profitable; say exactly that. An open job whose costs are ahead of its billing is not "losing money": give what has been spent and what has been billed. An open job is heading for a loss only when its forecastMarginPct is below zero.
- Only a completed job can be under budget. An open job that has spent less than its estimate is not under budget, it is unfinished. Where an open job has spentOfEstimatePct instead of a variance, describe it as spend so far against the estimate ("$8,000 spent of an $11,500 estimate").
- Do not guess at causes. Say what the numbers show, not why they might be that way. If something looks worth checking, say what to check.
- There is one cost estimate per job and no estimate per category. costByCategory says where the money went, never which category ran over. Never say an overrun "came from" a category, or from all of them.
- When a job has "estimateSetFromTargetMargin": true, its estimatedCost is a budget worked out from the target margin, not an estimate the contractor priced. Never say that job went over its estimate or overran it, and never lead with it for that reason. If its cost is above that figure, say it cost more than the target margin allows, and give its marginPct.
- If a number is missing (no estimate on file, for example), say so plainly instead of guessing.
- Do not give tax, legal, or accounting advice. Only report what happened on these jobs.

What to write:
- Lead with the most consequential thing for the owner: an open job whose forecastMarginPct is below zero (the lowest first), or a completed job that lost money, if there is one; otherwise the job furthest over its estimate; otherwise the most important change since last week.
- Write like a sharp project manager talking to the owner. Plain English, specific dollar amounts, no jargon.
- 3 to 5 short paragraphs, then a one-line closer. When weekOverWeek shows no changes, keep it to 2 short paragraphs: the reader has seen these job-to-date figures before.
- Write about the jobs, not about the data. Never explain to the reader what kind of figures these are ("these are job-to-date totals") or restate that nothing changed; the section above already says so.

Format:
- Plain text only. No markdown, no headings, no bullets.
- No subject line, no greeting, no sign-off. Start with your first sentence.
- Do not use em dashes or en dashes. Use commas, colons or full stops.`;

export async function generateWeeklyDigest(
  metrics: ConnectionMetrics,
  companyName: string,
  weekOverWeek: WeekOverWeekReport,
  /** Epoch ms the write-up must be finished by (see aiAttemptPlan). */
  deadline?: number,
  /** Jobs whose cost estimate was set from the target margin, not priced by the contractor. */
  targetFilledEstimates: ReadonlySet<string> = new Set()
): Promise<string> {
  const inBrief = new Set(metrics.briefJobIds);
  // Running over a budget worked out from the target margin isn't an
  // estimate overrun: the contractor never priced it. The model is told
  // which estimates those are, so it can say what's true.
  const marked = <T extends { jobId: string }>(j: T) =>
    targetFilledEstimates.has(j.jobId) ? { ...j, estimateSetFromTargetMargin: true } : j;
  const dh = metrics.briefDataHealth;
  const modelJobs = metrics.jobs.filter((j) => inBrief.has(j.jobId)).map(withoutOpenJobUnderspend).map(marked);
  const prompt = `Company: ${companyName}
Week starting: ${metrics.weekStarting.toISOString().slice(0, 10)}

Job-to-date figures for the jobs that matter now, plus what changed since the previous brief. Write the narrative as described.

${JSON.stringify(
  {
    totals: metrics.totals,
    jobs: modelJobs,
    topConcerns: metrics.topConcerns.map(withoutOpenJobUnderspend).map(marked),
    // Counts only. The full lists are on the Data Health page.
    dataHealth: {
      openJobsMissingEstimates: dh.jobsMissingEstimates.length,
      jobsWithRevenueButNoCosts: dh.jobsMissingCosts.length,
      untaggedJobCostsLast12Months: dh.untaggedJobCostCount,
      timeEntriesWithoutPayRate: dh.timeEntriesWithoutPayRate,
      possibleDuplicateCosts: dh.possibleDuplicates.length,
    },
    weekOverWeek: weekOverWeekForModel(weekOverWeek),
  },
  null,
  2
)}`;
  type Turn = { role: "user" | "assistant"; content: string };
  const ask = async (maxTokens: number, messages: Turn[] = [{ role: "user", content: prompt }]) => {
    const plan = aiAttemptPlan((deadline ?? Number.POSITIVE_INFINITY) - Date.now(), maxTokens > 1200 ? 75_000 : 45_000);
    if (!plan) throw new SummaryOutOfTimeError();
    try {
      return await aiClient(plan.timeoutMs, plan.retries).messages.create({
        model: AI_MODEL,
        max_tokens: maxTokens,
        system: SYSTEM_PROMPT,
        messages,
      });
    } catch (err) {
      // Given less than a request normally gets to fit the deadline: with
      // the usual time it may well have worked, so the run's timing is the
      // cause, not the AI.
      if (plan.limited) {
        throw new SummaryOutOfTimeError(
          `The summary request was cut short by the time left in this run: ${err instanceof Error ? err.message : "Unknown error"}`
        );
      }
      throw err;
    }
  };
  // A reply cut off at the token limit would go out mid-sentence in a paid
  // email. On a busy week it gets one retry with twice the room; if that is
  // cut off too, this throws rather than send a broken summary. About 45
  // seconds covers 1,200 tokens, and 75 covers 2,400.
  let maxTokens = 1200;
  let message = await ask(maxTokens);
  if (message.stop_reason === "max_tokens") message = await ask((maxTokens = 2400));
  if (message.stop_reason === "max_tokens") {
    throw new Error("The brief's write-up came back cut off at the length limit twice; not sending a partial brief.");
  }
  const draft = cleanDigestText(textOf(message));

  // The rules above are a request; this checks the reply against the ones
  // that have actually been broken (findSummaryProblems). A summary that
  // breaks one is sent back once with the sentences and what's wrong with
  // them. Whatever still breaks a rule after that is taken out, sentence by
  // sentence, so it never reaches a customer. Running short of time, or a
  // rewrite that fails, goes straight to taking the sentences out: this
  // check never costs the brief its summary or defers the send.
  const facts: SummaryFacts = {
    jobs: modelJobs,
    comparison: weekOverWeek?.noComparisonReason
      ? "skipped"
      : (weekOverWeek?.changes?.length ?? 0) > 0 || (weekOverWeek?.revenueAdded ?? 0) !== 0 || (weekOverWeek?.costAdded ?? 0) !== 0
        ? "changes"
        : "no_changes",
  };
  let text = draft;
  let problems = findSummaryProblems(text, facts);
  if (problems.length === 0) return text;
  console.warn(`digest: summary broke ${problems.length} rule(s) (${ruleList(problems)}); asking for a rewrite`);
  try {
    const rewrite = await ask(maxTokens, [
      { role: "user", content: prompt },
      { role: "assistant", content: draft },
      { role: "user", content: rewriteRequest(problems) },
    ]);
    if (rewrite.stop_reason !== "max_tokens") {
      const rewritten = cleanDigestText(textOf(rewrite));
      const rewrittenProblems = findSummaryProblems(rewritten, facts);
      if (rewritten.trim() && rewrittenProblems.length <= problems.length) {
        text = rewritten;
        problems = rewrittenProblems;
      }
    }
  } catch (err) {
    console.warn("digest: summary rewrite failed, removing the sentences instead:", err instanceof Error ? err.message : "Unknown error");
  }
  if (problems.length === 0) return text;
  console.warn(`digest: removing ${problems.length} sentence(s) that still broke a rule (${ruleList(problems)})`);
  text = withoutSentences(text, problems.map((p) => p.sentence));
  if (!text.trim()) throw new Error("Every sentence of the written summary broke the brief's rules, so it was left out.");
  return text;
}

function textOf(message: { content: { type: string; text?: string }[] }): string {
  const block = message.content.find((b) => b.type === "text");
  if (!block || typeof block.text !== "string") throw new Error("Claude did not return a text response for the digest.");
  return block.text;
}

/** The rules broken, for the logs: rule names only, never the text (it has job names and amounts in it). */
function ruleList(problems: SummaryProblem[]): string {
  return Array.from(new Set(problems.map((p) => p.rule))).join(", ");
}

/** Asks for the summary again with each broken rule pointed out. */
export function rewriteRequest(problems: SummaryProblem[]): string {
  return [
    "Some sentences in your summary break the rules:",
    ...problems.map((p) => `- "${p.sentence}" ${p.reason}`),
    "",
    "Rewrite the whole summary with these fixed, following every rule above. Keep the rest as it is. Reply with the summary only.",
  ].join("\n");
}

// Confidence levels below which a Claude-written profitability narrative
// would be trying to characterize data that doesn't support it - see
// generateWeeklyDigestForConnection below.
const TOO_LOW_FOR_NARRATIVE = new Set<DataHealthReport["overallConfidence"]>(["low", "insufficient_data"]);

/**
 * Plain-English, entirely deterministic explanation of why this week's email
 * doesn't have a profitability take in it - used instead of calling Claude
 * when company-wide Data Confidence is "low" or "insufficient_data". No AI
 * involved: every sentence here is built directly from counts already on
 * DataHealthReport, same numbers the Data Health page shows. This mirrors
 * the "structured facts first, AI narrative only as a secondary layer -
 * never AI alone" rule already applied to the dashboard, taken to its
 * logical conclusion: when the data can't support a trustworthy narrative,
 * skip the narrative entirely rather than have AI editorialize around gaps.
 */
export function buildDataHealthDigestBody(dataHealth: DataHealthReport, companyName: string): string {
  // What actually decides this email is sent: more than half of all jobs
  // have no calculable profit yet (see computeDataHealth). The notice used to
  // list other gaps instead, missing estimates and untagged expenses, which
  // don't affect that rating at all. A reader who fixed every item it named
  // got the same notice next week. So it now leads with the real reason and
  // names those jobs, then lists the other checks as secondary.
  const lines: string[] = [];
  const total = dataHealth.totalJobs;
  const without = dataHealth.jobsWithoutEnoughData;

  if (total === 0) {
    lines.push(
      `We didn't write a profitability summary for ${companyName} this week because there are no open or recently active jobs synced from QuickBooks yet. Once a job has invoices or costs on it, it shows up here.`
    );
    return lines.join("\n");
  }

  lines.push(
    `We didn't write a profitability summary for ${companyName} this week. ${without.length} of your ${total} open or recently active jobs don't have both revenue and costs in QuickBooks yet, so their profit can't be calculated, and a summary built on the rest would be misleading.`
  );
  lines.push("");
  lines.push("Jobs without enough data yet:");
  for (const job of without.slice(0, 8)) lines.push(`- ${job.jobName}: ${job.reason}`);
  if (without.length > 8) lines.push(`- and ${without.length - 8} more, listed on your Data Health page`);

  const bullet = (n: number | null, label: string) => (n == null || n === 0 ? null : `- ${n} ${label}`);
  const other = [
    bullet(dataHealth.jobsMissingEstimates.length, "open job(s) with no cost estimate on file"),
    bullet(dataHealth.staleJobs.length, "open job(s) with no synced activity in 30+ days"),
    bullet(dataHealth.completedJobsWithUnresolvedActivity.length, "completed job(s) with unresolved activity"),
    bullet(
      dataHealth.untaggedJobCostCount,
      `job cost(s) in the last 12 months not tagged to any job${
        dataHealth.untaggedJobCostAmount ? ` (${formatCurrency(dataHealth.untaggedJobCostAmount)})` : ""
      }`
    ),
    bullet(
      dataHealth.unresolvedExpenseCount,
      `expense(s) tagged to a customer we don't recognize as one of your jobs${
        dataHealth.unresolvedExpenseAmount ? ` (${formatCurrency(dataHealth.unresolvedExpenseAmount)})` : ""
      }`
    ),
    bullet(dataHealth.timeEntriesWithoutPayRate, "time entry(ies) from employees with no cost rate set in QuickBooks"),
    bullet(dataHealth.possibleDuplicates.length, "possible duplicate cost(s)"),
  ].filter((l): l is string => l != null);

  if (other.length > 0) {
    lines.push("");
    lines.push("Also worth a look, though these don't stop the summary:");
    lines.push(...other);
  }

  lines.push("");
  lines.push(
    "The summary comes back once most jobs have both invoices and costs in QuickBooks. That usually means tagging expenses and bills to the right Project. The full breakdown is always current on your Data Health page."
  );

  return lines.join("\n");
}

/**
 * Single entry point both the manual "Generate this week's digest" button
 * and the weekly-email cron job call, so the narrative-vs-Data-Health
 * decision lives in exactly one place. Computes metrics via the same
 * deterministic engine either way; only branches on whether to spend an AI
 * call on the narrative.
 */
export async function generateWeeklyDigestForConnection(
  connectionId: string,
  weekStarting: Date,
  companyName: string,
  opts: {
    /**
     * The weekly send: if the AI write-up fails, send the brief without it
     * rather than fail. Every figure in it is arithmetic on stored numbers
     * and doesn't need the AI, and an AI outage used to use up every due
     * company's attempts for the week. The Generate button leaves this off,
     * so its user sees the error and can try again.
     */
    allowMissingSummary?: boolean;
    /** Epoch ms the AI write-up must be finished by. Defaults to 105 seconds from now, inside a 120 second route. */
    deadline?: number;
    /**
     * The weekly send, when a later run can still send this week's brief:
     * a summary lost to the run's deadline (SummaryOutOfTimeError) is thrown
     * so the company is tried again in the next run, instead of going out
     * without it. A real AI failure still sends without it.
     */
    deferWhenOutOfTime?: boolean;
    /** A summary an earlier try at this week's send wrote (summaryToReuse), used instead of writing a new one. */
    storedSummary?: string | null;
  } = {}
): Promise<{
  narrative: string;
  kind: "narrative" | "data_health";
  metrics: ConnectionMetrics & { weekOverWeek: ReturnType<typeof weekOverWeekForModel> };
  /** The written part alone (AI summary or Data Health notice), for the HTML email. */
  body: string;
  weekOverWeek: WeekOverWeekReport;
  /** The money line the brief leads with; null if the feed couldn't be worked out this week. */
  headline: BriefHeadline | null;
  /** The jobs behind the email's tiles, on the feed's rules. */
  tiles: BriefTileJobs;
  /** True when the AI write-up failed and `body` says so instead. */
  summaryMissing: boolean;
}> {
  const deadline = opts.deadline ?? Date.now() + 105_000;
  // When these figures were read, stored with them: next week's brief
  // compares this with the dates a change of basis was made (see
  // basisChangeSince), and the row's own createdAt is its first save.
  const builtAt = new Date();
  const metrics = await computeConnectionMetrics(connectionId, weekStarting);

  // The comparison point is the most recent brief from an EARLIER week.
  // Strictly earlier, so regenerating this week's brief compares against
  // last week rather than against itself. If a week was skipped, this
  // compares against the last one that exists, and the section's heading
  // names that week so the gap is visible rather than implied away.
  const [prior, connection, targetFilled] = await Promise.all([
    prisma.weeklyDigest.findFirst({
      where: { connectionId, weekStarting: { lt: weekStarting } },
      orderBy: { weekStarting: "desc" },
      select: { weekStarting: true, metrics: true, createdAt: true },
    }),
    prisma.quickBooksConnection.findUnique({
      where: { id: connectionId },
      select: { laborBurdenSetAt: true, basisChangedAt: true, syncVersion: true, rebuildRequestedAt: true, lastFullSyncAt: true },
    }),
    prisma.job.findMany({ where: { connectionId, estimatedCostSource: "target_margin" }, select: { id: true } }),
  ]);
  const basis: BasisInfo = {
    laborBurdenSetAt: connection?.laborBurdenSetAt ?? null,
    basisChangedAt: connection?.basisChangedAt ?? null,
    syncVersion: connection?.syncVersion ?? null,
  };
  const weekOverWeek = computeWeekOverWeek(prior, metrics, basis);
  const changesSection = renderWeekOverWeek(weekOverWeek);

  // The headline: the Profit Opportunity Feed in one line, and what's new in
  // it since the last brief, compared on the same terms as "What changed".
  // A failure here never stops the brief.
  let headline: BriefHeadline | null = null;
  let feedSnapshot: BriefOpportunitySnapshot | null = null;
  try {
    const { feed } = await getOpportunityData(connectionId, new Date());
    feedSnapshot = snapshotFromFeed(feed);
    headline = computeBriefHeadline(feedSnapshot, prior?.metrics ?? null, companyName, {
      priorCreatedAt: prior?.createdAt ?? null,
      ...basis,
    });
  } catch (err) {
    console.error(`digest: opportunity headline failed for ${connectionId}:`, err instanceof Error ? err.message : "Unknown error");
  }
  const tiles = briefTileJobs(metrics, { targetFilledEstimates: targetFilled.map((j) => j.id), feed: feedSnapshot });

  // Stored with the snapshot. Next week's comparison reads `jobs` and
  // `opportunities`, and checks the basis fields below; the rest is for the
  // record: what the brief said changed, alongside the figures it was
  // computed from.
  const stored = {
    ...metrics,
    weekOverWeek: weekOverWeekForModel(weekOverWeek),
    ...(feedSnapshot ? { opportunities: feedSnapshot } : {}),
    builtAt: builtAt.toISOString(),
    syncVersion: connection?.syncVersion ?? null,
    // Settings changed how jobs are read and the rebuild hasn't synced yet:
    // these are the old figures, so next week mustn't compare with them.
    ...(connection && rebuildPending(connection) ? { basisPending: true } : {}),
  };
  const lead = headline ? `${headline.headline}\n\n` : "";

  // The changes section goes on both kinds of brief. It is arithmetic on
  // stored numbers, so it stays trustworthy even in a week when the data is
  // too thin for the AI narrative to be.
  //
  // Judged on the jobs the brief is about, not on the company's whole
  // history: old jobs that were never fully tagged must not silence the
  // brief for jobs that are.
  if (TOO_LOW_FOR_NARRATIVE.has(metrics.briefDataHealth.overallConfidence)) {
    const body = buildDataHealthDigestBody(metrics.briefDataHealth, companyName);
    // No money headline on a week the data can't support one: the snapshot
    // is still stored for next week's comparison, but not shown.
    return {
      narrative: `${changesSection}\n\n${body}`,
      kind: "data_health",
      metrics: stored,
      body,
      weekOverWeek,
      headline: null,
      tiles,
      summaryMissing: false,
    };
  }

  let body: string;
  let summaryMissing = false;
  try {
    body = opts.storedSummary?.trim()
      ? opts.storedSummary
      : await generateWeeklyDigest(metrics, companyName, weekOverWeek, deadline, new Set(targetFilled.map((j) => j.id)));
  } catch (err) {
    if (!opts.allowMissingSummary) throw err;
    if (opts.deferWhenOutOfTime && err instanceof SummaryOutOfTimeError) throw err;
    console.error(`digest: summary failed for ${connectionId}, sending without it:`, err instanceof Error ? err.message : "Unknown error");
    body = SUMMARY_UNAVAILABLE;
    summaryMissing = true;
  }
  return { narrative: `${lead}${changesSection}\n\n${body}`, kind: "narrative", metrics: stored, body, weekOverWeek, headline, tiles, summaryMissing };
}
