import type { Metadata } from "next";
import Link from "next/link";
import {
  Conspicuous,
  LegalList,
  LegalPage,
  LegalSection,
  LegalSub,
  LEGAL_LAST_UPDATED,
  MailingAddress,
  SupportEmail,
} from "@/components/marketing/Legal";
import {
  PARTNER_COMMISSION_MONTHS,
  PARTNER_TIERS,
  PLANS,
  REFERRAL_QUALIFY_DAYS,
  TRIAL_DAYS,
  TRIAL_EXTENSION_DAYS,
} from "@/lib/plans";
import { COMPANY_LEGAL_NAME, COMPANY_MAILING_ADDRESS } from "@/lib/company";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern use of JobProfitAI, operated by PWL Solutions LLC: accounts, the QuickBooks connection, subscriptions and automatic renewal, AI features, referral and partner programs, and liability.",
  alternates: { canonical: "/terms" },
};

const pi = PLANS.profit_intelligence;
const pro = PLANS.profit_intelligence_pro;
const tiersAscending = [...PARTNER_TIERS].reverse();
/** "20% while 1 to 9 of your referred clients are paying, 25% while ..." */
const tierSentence = tiersAscending
  .map((t, i) => {
    const next = tiersAscending[i + 1];
    const range = next
      ? `${t.minPayingClients} to ${next.minPayingClients - 1}`
      : `${t.minPayingClients} or more`;
    return `${t.ratePct}% while ${range} of your referred clients are paying`;
  })
  .reduce((acc, part, i, all) => (i === 0 ? part : `${acc}${i === all.length - 1 ? ", and " : ", "}${part}`), "");

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated={LEGAL_LAST_UPDATED}
      intro={
        <>
          <p>
            These Terms of Service (the “Terms”) are a binding agreement between you and PWL
            Solutions LLC, an Indiana limited liability company (“PWL Solutions,” “we,” “us,” or
            “our”), which operates JobProfitAI, including the website at jobprofitai.com, the web
            application, the Weekly Profit Brief and related emails, and any related services
            (together, the “Service”).
          </p>
          <p>
            By creating an account, connecting a QuickBooks Online company, starting a trial,
            subscribing, or otherwise using the Service, you agree to these Terms and to our{" "}
            <Link href="/privacy" className="font-medium text-jp-blue hover:underline">
              Privacy Policy
            </Link>
            . If you use the Service on behalf of a business, “you” means that business, and you
            confirm that you are authorized to accept these Terms for it. If you do not agree, do
            not use the Service.
          </p>
          <p>
            Please read Section 5 (Subscriptions, automatic renewal and cancellation), Section 11
            (Disclaimers) and Section 12 (Limitation of liability) carefully. They affect your
            rights.
          </p>
        </>
      }
    >
      <LegalSection id="service" title="1. What the Service does">
        <p>
          JobProfitAI connects to a QuickBooks Online company that you authorize, copies
          job-related accounting data from it, and uses that data to calculate and display job
          profitability, estimate comparisons, data-quality checks, trends and, on some plans,
          forecasts and cross-job comparisons. It also produces written explanations and
          recommendations, some of which are generated by artificial intelligence (see Section 8),
          and can send you a Weekly Profit Brief by email.
        </p>
        <p>
          The Service only reads from QuickBooks. It does not create, change or delete records in
          your QuickBooks company. The Service is an informational and analytical tool. It is not
          accounting, bookkeeping, tax, legal, financial or investment advice, and it does not
          replace a qualified professional. Decisions you make using the Service are yours.
        </p>
        <p>
          The Service is intended for businesses and the people who work for them. It is not
          intended for personal, family or household use, and you must be at least 18 years old to
          use it.
        </p>
      </LegalSection>

      <LegalSection id="accounts" title="2. Your account">
        <LegalList>
          <li>
            You must give accurate information when you sign up and keep your email address
            current. Some features, including the Weekly Profit Brief, stay off until you confirm
            your email address.
          </li>
          <li>
            You are responsible for keeping your password confidential and for all activity under
            your account. Tell us promptly at <SupportEmail /> if you believe your account has
            been accessed without your permission.
          </li>
          <li>
            An account is for the business that holds it. Give people their own login with team
            invitations rather than sharing yours, and do not create accounts to get additional
            free trials. Each QuickBooks company can have one free trial.
          </li>
          <li>
            If you invite team members, you are responsible for their use of the Service under your
            account and for making sure they may see the data in it. You can remove anyone at any
            time. Team members can&rsquo;t manage billing, the team or the account.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection id="quickbooks" title="3. The QuickBooks connection">
        <p>
          You connect QuickBooks Online through Intuit’s own authorization process. You confirm
          that you own the QuickBooks company you connect, or are authorized by its owner to
          connect it and to share its data with us for the purposes described in these Terms and
          our Privacy Policy.
        </p>
        <p>
          You can disconnect at any time from Settings, or from within your Intuit account.
          Disconnecting stops syncing and stops the Weekly Profit Brief for that company. Data
          already copied into JobProfitAI stays in your account until you delete your account (see
          Section 13) so you can reconnect later without losing history.
        </p>
        <p>
          Your use of QuickBooks Online is governed by your agreement with Intuit. JobProfitAI is
          not made, endorsed or certified by Intuit. QuickBooks and Intuit are trademarks of
          Intuit Inc. The Service depends on Intuit’s systems and programming interfaces, and we
          are not responsible for Intuit outages, changes Intuit makes to what data is available,
          or the accuracy of data in your QuickBooks company.
        </p>
      </LegalSection>

      <LegalSection id="trial" title="4. Free trial">
        <p>
          New accounts get a free trial of {TRIAL_DAYS} days with the features and limits of{" "}
          {pro.name}. No payment details are needed to start. Near the end of the trial we may
          offer a one-time extension of {TRIAL_EXTENSION_DAYS} days in exchange for completing a
          short feedback survey. The extension is available once per account.
        </p>
        <p>
          When the trial ends, the analysis features switch off unless you subscribe. Your account
          and your data are not deleted when a trial ends. You will not be charged at the end of a
          trial, because no payment method is collected for it. We may change, limit or end the
          trial offer for new accounts at any time.
        </p>
      </LegalSection>

      <LegalSection id="billing" title="5. Subscriptions, automatic renewal and cancellation">
        <LegalSub title="Plans and prices">
          <p>
            We currently offer two monthly plans: {pi.name} at {pi.priceLabel} per month, and{" "}
            {pro.name} at {pro.priceLabel} per month. Each plan’s features and limits (such as the
            number of QuickBooks companies you can connect) are described on our{" "}
            <Link href="/pricing" className="font-medium text-jp-blue hover:underline">
              Pricing page
            </Link>{" "}
            and in your Billing page. Prices are in US dollars and do not include taxes. You are
            responsible for any sales, use or similar taxes that apply, and where we are required
            to collect them they will be shown on your invoice.
          </p>
        </LegalSub>
        <LegalSub title="Automatic renewal">
          <p className="font-semibold text-jp-ink">
            Your subscription renews automatically every month, and your payment method is charged
            the then-current monthly price for your plan at the start of each monthly billing
            period, until you cancel.
          </p>
          <p>
            Payments are processed by Stripe. By subscribing, you authorize us, through Stripe, to
            charge your payment method for each renewal. Your first charge happens when you
            subscribe, and later charges happen on the same day of each following month.
          </p>
        </LegalSub>
        <LegalSub title="How to cancel">
          <p>
            You can cancel online at any time, with no phone call and no notice period: open
            Billing in your JobProfitAI account, choose Manage Billing, and cancel in the Stripe
            billing portal. If you cannot access your account, email <SupportEmail /> from the
            address on the account and we will cancel it for you. Cancellation takes effect at the
            end of the billing period you have already paid for. You keep access until then and are
            not charged again.
          </p>
        </LegalSub>
        <LegalSub title="Changing plans">
          <p>
            You can switch plans from the Stripe billing portal. Stripe prorates the change, which
            means you may be charged the difference right away or receive a credit toward future
            invoices. If you move to a plan with lower limits, nothing is deleted, but some
            features may stop working, and you cannot connect additional QuickBooks companies while
            you are over your plan’s limit.
          </p>
        </LegalSub>
        <LegalSub title="Refunds">
          <p>
            Except where the law requires otherwise, payments are non-refundable, and we do not
            give refunds or credits for partial months, unused features or periods when you did not
            use the Service. We may choose to give a refund or credit in a particular case. Doing
            so does not create an obligation to do the same in the future.
          </p>
        </LegalSub>
        <LegalSub title="Failed payments">
          <p>
            If a renewal payment fails, Stripe will retry it and we will let you know by email.
            You keep access while payment is being retried. If payment cannot be collected, your
            access to the paid features is paused until the balance is paid or you choose a plan
            again. Your data is not deleted because a payment failed.
          </p>
        </LegalSub>
        <LegalSub title="Price changes">
          <p>
            We may change our prices. We will email you at least 30 days before a price change
            applies to your subscription, and the new price will take effect at your next renewal
            after that notice period. If you do not want to pay the new price, you can cancel
            before it takes effect.
          </p>
        </LegalSub>
      </LegalSection>

      <LegalSection id="your-data" title="6. Your data">
        <p>
          “Your Data” means the information you or your QuickBooks company provide to the Service,
          including the accounting data we copy from QuickBooks, the settings and job details you
          enter, and the results we calculate from them. As between you and us, you own Your Data.
        </p>
        <p>
          You give us a limited permission to host, copy, process, analyze and display Your Data,
          and to share it with the service providers listed in our Privacy Policy, only as needed
          to provide, secure, support and improve the Service for you, and as the law requires. We
          do not sell Your Data and we do not use it to advertise to you or anyone else.
        </p>
        <p>
          Each account’s financial data is kept separate. Other customers cannot see it. Referring
          someone to JobProfitAI, or being their accountant, bookkeeper or partner, does not give
          anyone access to another account’s data. If you want someone else to see your numbers,
          you choose to share them, for example by adding them as a recipient of your Weekly
          Profit Brief. If you add recipients, you confirm that you are allowed to send them this
          information.
        </p>
        <p>
          We may create aggregated or de-identified information from use of the Service that does
          not identify you, your business, your customers or your jobs, and use it to operate and
          improve the Service.
        </p>
        <p>
          How we collect, use, share and protect information is described in our{" "}
          <Link href="/privacy" className="font-medium text-jp-blue hover:underline">
            Privacy Policy
          </Link>
          , which is part of these Terms.
        </p>
      </LegalSection>

      <LegalSection id="accuracy" title="7. Accuracy of results">
        <p>
          Every figure in JobProfitAI is calculated from the data in your QuickBooks company and
          the details you enter, such as estimates, target margins, job types and job status. If
          that data is incomplete, miscategorized, assigned to the wrong job or out of date, the
          results will be too. The Service includes data-quality checks to help you find these
          problems, but it cannot detect every one.
        </p>
        <p>
          Forecasts, projections, comparisons and benchmarks are estimates based on past and
          current data. They are not predictions we guarantee, and actual results can differ. You
          are responsible for checking any figure against your own records before relying on it
          for a pricing, bidding, lending, tax, legal or other significant business decision.
        </p>
      </LegalSection>

      <LegalSection id="ai" title="8. Artificial intelligence features">
        <p>
          Some text in the Service, including profit insights and the written summary in the
          Weekly Profit Brief, is generated by an AI model provided by a third party (currently
          Anthropic). To produce it, we send that provider the calculated profitability
          information for your jobs, which includes job names, the customer names attached to
          them, job types and calculated figures. Your QuickBooks login and access tokens are
          never sent.
        </p>
        <p>
          AI-generated text can be incomplete or wrong, even though the dollar amounts and
          percentages it refers to are calculated by our software, not by the AI model. Treat
          AI-generated explanations and recommendations as suggestions to review, not as
          professional advice, and check them against the job pages before acting on them.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" title="9. Acceptable use">
        <p>You agree not to, and not to let anyone else:</p>
        <LegalList>
          <li>connect a QuickBooks company or use data you are not authorized to use;</li>
          <li>
            access or try to access another account, or any data that is not yours, or probe,
            scan or test the Service for vulnerabilities, except as described in Section 10;
          </li>
          <li>
            interfere with or disrupt the Service, or put an unreasonable load on it, including
            through automated scraping or excessive requests;
          </li>
          <li>
            copy, modify, reverse engineer or decompile the Service, except to the extent the law
            allows despite this restriction;
          </li>
          <li>
            resell, sublicense or rent the Service, or use it to provide a service to others, or
            to build a competing product;
          </li>
          <li>
            create multiple accounts or use false information to obtain additional trials,
            referral credits or partner commissions; or
          </li>
          <li>use the Service in a way that violates any law or anyone else’s rights.</li>
        </LegalList>
      </LegalSection>

      <LegalSection id="security" title="10. Security and reporting problems">
        <p>
          We use reasonable administrative, technical and physical safeguards designed to protect
          Your Data. Our{" "}
          <Link href="/security" className="font-medium text-jp-blue hover:underline">
            Security page
          </Link>{" "}
          describes the controls actually in place. No system is perfectly secure, and we cannot
          guarantee that Your Data will never be accessed without authorization. If we learn of a
          security incident affecting Your Data, we will notify you as required by law.
        </p>
        <p>
          If you believe you have found a security vulnerability, please email <SupportEmail />{" "}
          with the details and do not access, change or delete data that is not yours while
          investigating it. We will not pursue action against good-faith reports made this way.
        </p>
      </LegalSection>

      <LegalSection id="disclaimers" title="11. Disclaimers">
        <Conspicuous>
          To the fullest extent permitted by law, the Service, including all calculations,
          forecasts, insights, AI-generated content and emails, is provided “as is” and “as
          available,” without warranties of any kind, whether express, implied or statutory,
          including any implied warranties of merchantability, fitness for a particular purpose,
          title, non-infringement and accuracy. We do not warrant that the Service will be
          uninterrupted, timely, secure or error-free, that any result will be accurate or
          complete, or that the Service will identify every problem with a job or with your data.
        </Conspicuous>
        <p>
          Some jurisdictions do not allow the exclusion of certain warranties, so some of these
          exclusions may not apply to you.
        </p>
      </LegalSection>

      <LegalSection id="liability" title="12. Limitation of liability">
        <Conspicuous>
          To the fullest extent permitted by law, PWL Solutions LLC and its members, managers,
          employees and agents will not be liable for any indirect, incidental, special,
          consequential, exemplary or punitive damages, or for any loss of profits, revenue,
          business, goodwill or data, or the cost of substitute services, arising out of or
          related to these Terms or the Service, even if we have been told such damages were
          possible.
        </Conspicuous>
        <Conspicuous>
          To the fullest extent permitted by law, our total liability for all claims arising out
          of or related to these Terms or the Service is limited to the greater of (a) the amounts
          you paid us for the Service in the 12 months before the event giving rise to the claim,
          and (b) one hundred US dollars ($100).
        </Conspicuous>
        <p>
          These limits apply to every kind of claim, whether in contract, tort (including
          negligence), strict liability or otherwise, and even if a limited remedy fails of its
          essential purpose. They do not limit liability that cannot be limited under applicable
          law, such as liability for fraud or for gross negligence or willful misconduct where the
          law does not permit a limit.
        </p>
      </LegalSection>

      <LegalSection id="termination" title="13. Ending your use of the Service">
        <LegalSub title="Deleting your account">
          <p>
            You can permanently delete your account at any time from Settings. Deleting your
            account revokes any live QuickBooks connection, cancels any active subscription
            immediately, and deletes your account data as described in our Privacy Policy.
            Deletion cannot be undone. Because deletion cancels your subscription immediately,
            you lose access to any remainder of a paid month, and that remainder is not refunded.
            If you want to keep access until the end of the month, cancel first and delete your
            account later.
          </p>
        </LegalSub>
        <LegalSub title="Suspension or termination by us">
          <p>
            We may suspend or end your access to the Service if you materially breach these Terms,
            if you do not pay amounts due, if your use creates a security or legal risk for us or
            others, or if the law requires it. Where it is reasonable to do so, we will notify you
            first and give you a chance to fix the problem. We may also discontinue the Service as
            a whole. If we do that for reasons other than your breach, we will give you at least
            30 days’ notice by email and refund any amount you prepaid for the period after the
            Service ends.
          </p>
        </LegalSub>
        <p>
          Sections 6 (as to aggregated information), 7, 8, 11, 12, 14, 16, 17 and 18, and any
          amounts owed, survive the end of these Terms.
        </p>
      </LegalSection>

      <LegalSection id="indemnity" title="14. Your responsibility for claims">
        <p>
          To the extent permitted by law, you will defend, indemnify and hold harmless PWL
          Solutions LLC and its members, managers and employees from any third-party claims,
          losses and reasonable costs (including reasonable attorneys’ fees) arising from (a) your
          connecting a QuickBooks company or sharing data you were not authorized to connect or
          share, (b) your sending the Weekly Profit Brief or other information to recipients you
          added, or (c) your violation of these Terms or of law. We will tell you promptly about
          any such claim and let you control its defense, although we may take part with our own
          counsel at our own cost.
        </p>
      </LegalSection>

      <LegalSection id="programs" title="15. Referral and partner programs">
        <LegalSub title="Customer referral program">
          <p>
            If someone signs up through your referral link, subscribes, and remains a paying
            customer for {REFERRAL_QUALIFY_DAYS} days without a full refund or chargeback, you earn
            a credit equal to one month of your own current plan. Credits are applied to your
            Stripe account balance and come off future JobProfitAI invoices automatically. If you
            are not subscribed when a credit is earned, it is held and applied when you subscribe.
            Credits have no cash value, cannot be transferred, and are not refundable. A referred
            account can be credited to only one referrer, and you cannot refer yourself or an
            account you control. If the payment that qualified a credit is later fully refunded or
            charged back, we may reverse the credit.
          </p>
        </LegalSub>
        <LegalSub title="Partner program">
          <p>
            Accounting and bookkeeping firms approved into our partner program earn a commission
            on the subscription payments of clients they refer. The commission rate is {tierSentence}
            , counted at the time each payment is made. Commission is calculated on subscription
            revenue actually collected, excluding taxes, for each referred client’s first{" "}
            {PARTNER_COMMISSION_MONTHS} paid months. The rate that applies when a payment is made
            is fixed for that payment. Commission on a payment that is fully refunded or charged
            back before we pay it out is reversed. If we have already paid it, we will review it
            with you before making any adjustment.
          </p>
          <p>
            Commissions are recorded in your partner dashboard and paid by us manually to the
            payout contact you provide. We may ask for tax information (such as a Form W-9) before
            paying, and you are responsible for your own taxes on commissions. We may approve or
            decline partner applications at our discretion, and we may suspend a partner or
            withhold commissions connected with fraud, self-referral, misleading promotion or a
            breach of these Terms. Partners may not describe JobProfitAI inaccurately, offer
            discounts we have not authorized, or make claims on our behalf. Any complimentary
            account offered to partners is provided at our discretion and set up with you
            directly.
          </p>
        </LegalSub>
        <LegalSub title="Both programs">
          <p>
            Referral status gives no one access to another account’s data. We may change or end
            either program for the future by updating these Terms or the program page. Credits
            and commissions already earned under the terms in effect at the time will be honored,
            except where they are reversed for the reasons described above.
          </p>
        </LegalSub>
      </LegalSection>

      <LegalSection id="ip" title="16. Our intellectual property and feedback">
        <p>
          We and our licensors own the Service, including its software, design, text and
          trademarks. Subject to these Terms, we give you a limited, non-exclusive,
          non-transferable right to use the Service for your internal business purposes while
          your account is in good standing. We keep all rights not expressly given to you.
        </p>
        <p>
          If you send us suggestions or feedback, including through the feedback survey or
          in-app feedback form, we may use them without any obligation to you. We will not
          publicly attribute feedback to you, or publish it as a testimonial, without your
          separate permission.
        </p>
      </LegalSection>

      <LegalSection id="law" title="17. Governing law and disputes">
        <p>
          These Terms and any dispute arising out of or related to them or the Service are
          governed by the laws of the State of Indiana, without regard to its conflict-of-laws
          rules. Before bringing a formal claim, you agree to email <SupportEmail /> with a
          description of the dispute and give us 30 days to try to resolve it informally.
        </p>
        <p>
          Any claim that is not resolved informally must be brought exclusively in the state or
          federal courts located in the State of Indiana, and you and we consent to the personal
          jurisdiction of those courts. Either of us may bring an individual claim in small claims
          court if it qualifies. Nothing in this section prevents either of us from seeking
          urgent injunctive relief to protect intellectual property or data.
        </p>
      </LegalSection>

      <LegalSection id="general" title="18. General terms">
        <LegalList>
          <li>
            <span className="font-medium text-jp-ink">Changes to these Terms.</span> We may update
            these Terms. If a change is material, we will email the address on your account at
            least 30 days before it takes effect, except for changes required by law or made for
            security reasons, which may take effect sooner. The “Last updated” date above shows
            when these Terms last changed. Continuing to use the Service after a change takes
            effect means you accept it. If you do not accept a change, you can cancel before it
            takes effect.
          </li>
          <li>
            <span className="font-medium text-jp-ink">Changes to the Service.</span> We may add,
            change or remove features. If we remove a core feature of your plan, we will tell you
            in advance where reasonably possible.
          </li>
          <li>
            <span className="font-medium text-jp-ink">Notices.</span> We send notices to the email
            address on your account. You can send notices to <SupportEmail />, or by mail to{" "}
            {COMPANY_LEGAL_NAME}, {COMPANY_MAILING_ADDRESS}. You agree to receive our
            communications electronically.
          </li>
          <li>
            <span className="font-medium text-jp-ink">Events outside our control.</span> We are
            not responsible for delays or failures caused by events beyond our reasonable control,
            including outages at Intuit, our hosting, database, payment, email or AI providers, or
            the internet generally.
          </li>
          <li>
            <span className="font-medium text-jp-ink">Assignment.</span> You may not transfer these
            Terms without our written consent. We may transfer them in connection with a merger,
            acquisition or sale of all or part of our business, and will notify you if we do.
          </li>
          <li>
            <span className="font-medium text-jp-ink">Entire agreement.</span> These Terms,
            together with the Privacy Policy and any plan details shown at checkout, are the entire
            agreement between you and us about the Service and replace any earlier agreements
            about it. If any provision is found unenforceable, it will be enforced to the maximum
            extent possible and the rest of these Terms will remain in effect. Our not enforcing a
            provision is not a waiver of it. There are no third-party beneficiaries of these Terms.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection id="contact" title="19. Contact">
        <p>
          JobProfitAI is operated by PWL Solutions LLC, an Indiana limited liability company.
          Questions about these Terms can be sent to <SupportEmail /> or through our{" "}
          <Link href="/contact" className="font-medium text-jp-blue hover:underline">
            contact form
          </Link>
          . Our mailing address is:
        </p>
        <MailingAddress />
      </LegalSection>
    </LegalPage>
  );
}
