import Link from "next/link";

export const metadata = {
  title: "Terms of Service — JobProfitAI",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <Link href="/" className="text-sm text-brand hover:underline">
        &larr; Back to JobProfitAI
      </Link>
      <h1 className="mt-4 text-3xl font-bold text-navy">Terms of Service</h1>
      <p className="mt-2 text-sm text-gray-500">Last updated: August 7, 2026</p>

      <div className="prose prose-sm mt-8 max-w-none text-gray-700">
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of
          JobProfitAI (the &quot;Service&quot;), operated by PWL Solutions LLC, an
          Indiana limited liability company (&quot;JobProfitAI,&quot; &quot;we,&quot;
          &quot;us,&quot; or &quot;our&quot;). By creating an account or using the Service,
          you agree to these Terms.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">1. The Service</h2>
        <p>
          JobProfitAI connects to your QuickBooks Online account (read-only) and
          generates a periodic, AI-written digest summarizing job-cost accuracy
          and profitability based on the data in your QuickBooks company file.
          The Service is a reporting and informational tool. It does not modify
          your QuickBooks data, file taxes, or provide accounting, legal, or
          financial advice.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">2. Accounts</h2>
        <p>
          You must provide accurate information when creating an account and are
          responsible for maintaining the confidentiality of your login
          credentials and for all activity under your account. You must be
          authorized to connect the QuickBooks Online company you connect to the
          Service.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">3. QuickBooks connection</h2>
        <p>
          Connecting QuickBooks Online is done through Intuit&apos;s official OAuth
          authorization flow. You control this connection and may disconnect it
          at any time from your JobProfitAI dashboard or directly from your
          Intuit account. Your use of QuickBooks Online remains subject to
          Intuit&apos;s own terms, separate from these Terms.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">4. Subscription and billing</h2>
        <p>
          Paid features of the Service are billed on a subscription basis as
          described at checkout. Fees are non-refundable except as required by
          law or as we expressly state otherwise. You may cancel at any time;
          cancellation takes effect at the end of the then-current billing
          period.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to connect a QuickBooks account you are not authorized to access.</li>
          <li>Attempt to interfere with, disrupt, or gain unauthorized access to the Service or its underlying systems.</li>
          <li>Reverse-engineer, resell, or use the Service to build a competing product.</li>
          <li>Use the Service in a way that violates applicable law.</li>
        </ul>

        <h2 className="mt-8 text-lg font-semibold text-navy">6. AI-generated content</h2>
        <p>
          Digest narratives are generated by an AI model based strictly on
          numbers computed from your synced QuickBooks data. While we design the
          system to ground every statement in your actual data, you are
          responsible for independently verifying any figure before relying on
          it for a business, financial, tax, or legal decision. The digest is
          informational only and is not accounting, tax, or legal advice.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">7. Data and privacy</h2>
        <p>
          Our collection and use of your information is described in our{" "}
          <Link href="/privacy" className="text-brand hover:underline">
            Privacy Policy
          </Link>
          , which is incorporated into these Terms by reference.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">8. Disclaimers</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS
          OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT GUARANTEE THAT THE
          SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT DIGEST CONTENT WILL
          BE FREE OF INACCURACY, INCLUDING DUE TO INCOMPLETE OR INCORRECT DATA IN
          YOUR CONNECTED QUICKBOOKS ACCOUNT.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">9. Limitation of liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, PWL SOLUTIONS LLC WILL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
          PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUE, ARISING FROM YOUR
          USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM RELATING TO THE
          SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE
          THE CLAIM AROSE.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">10. Termination</h2>
        <p>
          You may stop using the Service and disconnect your QuickBooks
          connection at any time. We may suspend or terminate your access if you
          violate these Terms or if required by law.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">11. Changes to these Terms</h2>
        <p>
          We may update these Terms from time to time. If we make material
          changes, we will update the &quot;Last updated&quot; date above and, where
          appropriate, notify you directly.
        </p>

        <h2 className="mt-8 text-lg font-semibold text-navy">12. Governing law</h2>
        <p>These Terms are governed by the laws of the State of Indiana, without regard to its conflict-of-laws principles.</p>

        <h2 className="mt-8 text-lg font-semibold text-navy">13. Contact us</h2>
        <p>
          Questions about these Terms can be sent to{" "}
          <a href="mailto:support@jobprofitai.com" className="text-brand hover:underline">
            support@jobprofitai.com
          </a>
          , or to PWL Solutions LLC.
        </p>

        <p className="mt-10 rounded-lg border border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">
          Note: these Terms are a working draft prepared to accurately describe
          how JobProfitAI currently operates. Have them reviewed by a licensed
          attorney before relying on them for real paying customers.
        </p>
      </div>
    </main>
  );
}
